name: Build PBRP Recovery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build PBRP Recovery with Provided Device Info
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set Swap Space (Optional)
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: Build PBRP
      uses: mlm-games/pbrp-build-action@main
      with:
        MANIFEST_BRANCH: 'android-12.1'
        DEVICE_TREE: 'https://github.com/zzdwymk/recovery_device_realme_RMX3700'
        DEVICE_TREE_BRANCH: 'orangefox-12.1'
        DEVICE_NAME: 'RMX3700'
        DEVICE_PATH: 'device/realme/RMX3700'
        BUILD_TARGET: 'pbrp'   # Use 'pbrp' for Android 11 or above

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v3
      with:
        name: PBRP-Recovery
        path: ${{ env.OUTPUT_DIR }}/*.img
